services:
  upchuk_gelf.transport_factory:
    class: Drupal\upchuk_gelf\GelfTransportFactory
  upchuk_gelf.transport:
    class: Gelf\Transport\UdpTransport
    factory: 'upchuk_gelf.transport_factory:getTransport'
  upchuk_gelf.publisher:
    class: Gelf\Publisher
    arguments: ['@upchuk_gelf.transport']
  monolog.formatter.gelf:
    class: Drupal\upchuk_gelf\GelfMessageFormatter
  # "Install" the gelf handler.
  monolog.handler.gelf:
    class: Monolog\Handler\GelfHandler
    arguments: ['@upchuk_gelf.publisher']

parameters:
  monolog.channel_handlers:
    default:
      handlers:
        - name: 'gelf'
          formatter: 'gelf'
        - name: 'drupal.dblog'
          formatter: 'line'
    php:
      handlers:
        - name: 'gelf'
          formatter: 'gelf'
        - name: 'drupal.dblog'
          formatter: 'line'
    image:
      handlers:
        - name: 'drupal.dblog'
          formatter: 'line'
    cron:
      handlers:
        - name: 'drupal.dblog'
          formatter: 'line'
    'page not found':
      handlers:
        - name: 'drupal.dblog'
          formatter: 'line'
